# Generated by Django 4.2.2 on 2023-06-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='isGood',
            new_name='isgood',
        ),
    ]
