# Generated by Django 4.2.2 on 2023-06-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_isgood_snack_isgood'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='name',
            field=models.CharField(default='blank', max_length=40),
            preserve_default=False,
        ),
    ]
